# Generated by Django 4.2.1 on 2023-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=6, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=33)),
                ('type', models.CharField(max_length=7, choices=[('inflow', 'inflow'), ('outflow', 'outflow')])),
                ('category', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
